# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
np
x=np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Create a vector with values ranging from 10 to 49

In [3]:
np
y=np.arange(10,50)
print(y)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


4. Find the shape of previous array in question 3

In [4]:
np
arr=np.array(y)
print(arr.shape)

(40,)


5. Print the type of the previous array in question 3

In [5]:
np
arr=np.array(y)
print(arr.dtype)

int32


6. Print the numpy version and the configuration


In [6]:
np
print(np.__version__)

1.19.2


7. Print the dimension of the array in question 3


In [7]:
np
a=np.array(y)
a.ndim

1

8. Create a boolean array with all the True values

In [8]:
np
b=np.array(y,dtype=bool)
print(b)

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True]


9. Create a two dimensional array




In [9]:
np
ar = np.arange(10,50).reshape(4,10)
ar

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

10. Create a three dimensional array



In [10]:
np
y=np.array([10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49])
ar = y.reshape(2,4,5)
ar

array([[[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [11]:
np
y=np.arange(10,50)
y=y[::-1]
print(y)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


12. Create a null vector of size 10 but the fifth value which is 1 

In [12]:
np
y=np.arange(10,50)
y[4]=1
print(y)

[10 11 12 13  1 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


13. Create a 3x3 identity matrix

In [13]:
np
x=np.identity(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [14]:
arr = np.array([1, 2, 3, 4, 5],dtype=float)
arr.dtype

dtype('float64')

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [15]:
np
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
multi=np.multiply(arr1,arr2)
print(multi)

[[ 0.  8.  3.]
 [28. 10. 72.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [16]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
xyz=arr1==arr2
print(xyz)

[[False False False]
 [False False False]]


17. Extract all odd numbers from arr with values(0-9)

In [17]:
np
a=np.array([0,1,2,3,4,5,6,7,8,9])
a[a%2==1]

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [18]:
np
a=np.array([0,1,2,3,4,5,6,7,8,9])
a[a%2==1-1]

array([0, 2, 4, 6, 8])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [19]:
np
arr=np.arange(10)
arr[5:9]=12
print(arr)

[ 0  1  2  3  4 12 12 12 12  9]


20. Create a 2d array with 1 on the border and 0 inside

In [20]:
np
z=np.ones((5,5))
z[1:-1,1:-1]=0
print(z)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [21]:
np
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr2d[1:2,1:2]=12
print(arr2d)

[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [22]:
np
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[:1,:2]=64
print(arr3d)


[[[64 64 64]
  [64 64 64]]

 [[ 7  8  9]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [23]:
np
data=np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
d=data[:1,:3]
print(d)


[[1 2 3]]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [24]:
np
data=np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
d=data[1:2,1:2]
print(d)

[[5]]


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [25]:
np
data=np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
d=data[:2,2:3]
print(d)

[[3]
 [6]]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [26]:
np
a=np.random.random((10,10))
print(a)
xmin,xmax=a.min,a.max
print("Min and Max")
print(xmin,xmax)

[[0.9868268  0.54851129 0.24985294 0.83365221 0.33304529 0.62967959
  0.92539751 0.0678512  0.98431102 0.49264657]
 [0.52731551 0.25154394 0.92706373 0.14153541 0.96093967 0.4486744
  0.26845158 0.23568486 0.17415839 0.42015844]
 [0.89525123 0.2852927  0.38350943 0.06260077 0.55042367 0.07767416
  0.18504997 0.42362171 0.58786034 0.43527982]
 [0.91429838 0.61634251 0.85801801 0.980858   0.80260505 0.08085902
  0.04659612 0.07874466 0.35935919 0.3459612 ]
 [0.17366748 0.36030159 0.43074126 0.065409   0.03644911 0.31035443
  0.52898024 0.90973005 0.17339906 0.89132206]
 [0.30187563 0.30219609 0.11336787 0.13872163 0.33302505 0.60697295
  0.42358286 0.49486356 0.69421873 0.56364509]
 [0.56466571 0.41788248 0.26350588 0.26689979 0.82573857 0.21688507
  0.655451   0.96740959 0.4778298  0.33723717]
 [0.03719237 0.12576297 0.36133771 0.5688033  0.83207592 0.10020549
  0.45269185 0.78745436 0.31055142 0.46496015]
 [0.29523949 0.22891958 0.34621285 0.68923343 0.01965478 0.59158449
  0.65665887 

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [27]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

print(np.intersect1d(a,b))

[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [28]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

c=np.where(a==b)
print(c)

(array([1, 3, 5, 7], dtype=int64),)


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [29]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
data[names != 'will']

array([[-0.27713571, -0.19725222,  0.21505897, -0.85358572],
       [ 0.13901799, -0.17734647, -0.39382777, -0.71776845],
       [-1.8982122 , -0.29229443, -0.70893283,  1.54927973],
       [-1.78478575, -0.84458024,  0.40019692, -0.73097704],
       [ 1.33701968, -0.74686353, -0.29925571, -1.77541325],
       [ 0.46866582,  0.30982267, -1.05889885, -1.93228517],
       [ 0.58336372, -1.25774597, -0.14449666,  1.31988136]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [30]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)

Result=(names!='Will')| (names!='jeo')

data[Result]

array([[-2.0042291 ,  0.79645599,  1.58716123, -0.13534146],
       [-0.54425914, -0.79474968,  0.71751756, -1.724051  ],
       [ 0.04023771, -1.22950323, -0.28030943, -0.56676416],
       [-0.74663624,  0.71389594, -0.53988028,  0.44040049],
       [ 0.25918436, -0.14823441, -0.60727795,  1.50361865],
       [ 1.17349992, -1.06702121,  0.89862115, -0.45210989],
       [-1.60008147, -0.04683308,  0.21503301, -0.24028116]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [31]:
rand_arr = np.random.uniform(1,15, size=(5,3))
print(rand_arr)

[[12.57789233  2.95217326  2.06269525]
 [ 6.66044121  9.48931567 13.99707974]
 [10.5750198  14.54888064  6.80467121]
 [11.844681    5.38843389  2.25215611]
 [ 6.4675944  14.99101271 12.47256877]]


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [32]:
rand_arr = np.random.uniform(1,16, size=(2,2,4))
print(rand_arr)

[[[ 5.0969918   5.15205024 12.26194565  9.84706013]
  [ 2.91659096  1.31763179  3.05760672 10.38834374]]

 [[13.38667878  2.82547397 15.76371444  8.21297538]
  [ 2.71727105 11.1185798  15.16662184 12.25289456]]]


33. Swap axes of the array you created in Question 32

In [33]:
rand_arr = np.random.uniform(1,16, size=(2,2,4))
np.swapaxes(rand_arr,2,1)

array([[[ 5.09610012,  7.25988051],
        [10.81546431,  8.56681843],
        [15.09135341,  3.6923023 ],
        [11.12191423, 14.16280541]],

       [[ 4.00301882,  5.8297626 ],
        [ 9.40923392,  8.83207033],
        [ 5.36638286,  9.45454003],
        [15.56143161, 11.51167254]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [34]:
a=np.arange(10)
print(a)
b=np.sqrt(a)
b[a < 0.5]=0
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [35]:
a=np.array([2,6,9,7,20,56,54,11,12,66,67,85])
b=np.array([63,5,22,59,44,52,88,25,22,50,88,47])
c=np.maximum(a,b)
print(c)

[63  6 22 59 44 56 88 25 22 66 88 85]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [36]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)
sorted(set(names))

['Bob', 'Joe', 'Will']

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [37]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])

c = np.setdiff1d(a, b)
print(c)

[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [38]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 


sampleArray = np.delete(sampleArray , 1, axis = 1) 


arr = np.array([[10,10,10]])

sampleArray = np.insert(sampleArray , 1, arr, axis = 1) 
print (sampleArray)

[[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [39]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])

z=np.dot(x,y)
print(z)

[[ 28.  64.]
 [ 67. 181.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [40]:
import numpy as np
rm = np.random.randint(1,20,size=(4,4))
np.cumsum(rm)
print(rm)

[[ 4 19 11 17]
 [19  2  5 10]
 [ 6  4 16 16]
 [18 19  4 13]]
