# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np
arr2=np.arange(10).reshape(2,5)
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [2]:
import numpy as np
arr1= np.array([[0,1,2,3,4],[5,6,7,8,9]])
arr2 = np.array([[1,1,1,1,1],[1,1,1,1,1]])
np.vstack((arr1,arr2))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [3]:
import numpy as np
arr1= np.array([[0,1,2,3,4],[5,6,7,8,9]])
arr2 = np.array([[1,1,1,1,1],[1,1,1,1,1]])
np.hstack((arr1,arr2))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [4]:
np
arr1=np.arange(10)
flattenarray=arr1.flatten()
flattenarray

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

# How to Convert higher dimension into one dimension?

#### Desired Output::

In [5]:
np
arr1=np.arange(15).reshape(3,5)
print(arr1)
a=arr1.ravel()
a

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [6]:
arr1=np.arange(15).reshape(5,3)
arr1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [7]:
np
arr1=np.arange(25).reshape(5,5)
print("Square Value of arr1 : \n",np.square(arr1))


Square Value of arr1 : 
 [[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]
 [400 441 484 529 576]]


## Question:8

### Create 5x6 an array and find the mean?

In [8]:
np
arr1=np.arange(30).reshape(5,6)
print("Mean of array",np.mean(arr1))

Mean of array 14.5


## Question:9

### Find the standard deviation of the previous array in Q8?

In [9]:
np
arr1=np.arange(30).reshape(5,6)
print("Standard Deviation of array",np.std(arr1))

Standard Deviation of array 8.65544144839919


## Question:10

### Find the median of the previous array in Q8?

In [10]:
np
arr1=np.arange(30).reshape(5,6)
print("Median of array",np.median(arr1))

Median of array 14.5


## Question:11

### Find the transpose of the previous array in Q8?

In [11]:
np
arr1=np.arange(30).reshape(5,6)
print("Transpose of array",np.transpose(arr1))

Transpose of array [[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [12]:
np
arr1=np.arange(16).reshape(4,4)
print(arr1)
print("Trace of array",np.trace(arr1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Trace of array 30


## Question:13

### Find the determinant of the previous array in Q12?

In [13]:
np
arr1=np.arange(16).reshape(4,4)
print("determinan of array",np.linalg.det(arr1))

determinan of array -2.9582283945787796e-30


## Question:14

### Find the 5th and 95th percentile of an array?

In [17]:
np
arr1=np.arange(100)
print("5th Percentile of array",np.percentile(arr1,[5]))
print("95th Percentile of array",np.percentile(arr1,[95]))

5th Percentile of array [4.95]
95th Percentile of array [94.05]


# Question:15

### How to find if a given array has any null values?

In [18]:
np
arr1=([[ 1. , 2.,3.],
 [3. ,np.nan,5.]])
arraysum = np.sum(arr1)
arraynan = np.isnan(arraysum)
print(arraynan)

True
